# Upload Python Package to Conda
name: Upload Python Package to Conda

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.- name: Publish Anaconda package to Anaconda.org
      - name: build and publish Anaconda package to Anaconda.org
        uses: BEFH/anaconda-publish@v1.5.1
        with:
          # Sub-directory with conda recipe
          subDir: conda-recipe
          # Anaconda access Token
          AnacondaToken: ${{ secrets.ANACONDAORG_API_TOKEN }}
          # Whether to publish to anaconda
          publish: true
          # Whether to convert linux build for windows
          convert_win: true
          # Whether to convert linux build for osx
          convert_osx: true
